
CREATE TABLE STAFF (
    STAFF_ID NUMBER PRIMARY KEY,
    STAFF_NAME VARCHAR2(100),
    SALARY NUMBER(10,2)
);
INSERT INTO STAFF VALUES (101, 'Rahul', 50000);
INSERT INTO STAFF VALUES (102, 'Amit', 75000);
INSERT INTO STAFF VALUES (103, 'Priya', 45000);
INSERT INTO STAFF VALUES (104, 'Neha', 90000);
INSERT INTO STAFF VALUES (105, 'Rohit', 65000);
INSERT INTO STAFF VALUES (106, 'Anjali', 85000);
INSERT INTO STAFF VALUES (107, 'Vikas', 55000);
INSERT INTO STAFF VALUES (108, 'Pooja', 70000);

COMMIT;

DECLARE
    CURSOR emp_cursor IS
        SELECT STAFF_NAME, SALARY
        FROM STAFF
        ORDER BY SALARY DESC
        FETCH FIRST 5 ROWS ONLY;

    V_NAME STAFF.STAFF_NAME%TYPE;
    V_SALARY STAFF.SALARY%TYPE;

BEGIN
    OPEN emp_cursor;

    LOOP
        FETCH emp_cursor INTO V_NAME, V_SALARY;

        EXIT WHEN emp_cursor%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Name: ' || V_NAME ||
            ' | Salary: ' || V_SALARY
        );
    END LOOP;

    CLOSE emp_cursor;

END;
/